[cmob-1518]/feature/start page
giorgimurgulia-space/QuizApp pull request #1
Opened 2023-05-24 09:42 UTC by giorgimurgulia-space

https://spaceneobank.atlassian.net/browse/CMOB-1518

2023-06-01 09:13 UTC, Gio481 commented
პრს სახელი არაა სწორი, [CMOB-1518] და feature აღარ უნდა სახელში და / არაა საჭირო გამოყოფა

2023-06-01 09:13 UTC, Gio481 commented
დეველოპზე უნდა გამოუშვა პრ

2023-06-01 09:54 UTC, Gio481 requested changes

2023-06-01 09:54 UTC, Gio481 commented on app/build.gradle
> +
არ უნდა გამოტოვება

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/local/database/model/dao/UserDao.kt
> +    suspend fun getByIdUser(userId: String): UserEntity
getUserById

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/local/database/model/dao/UserDao.kt
> +    suspend fun getByUsername(username: String): UserEntity
ამ ორ ფუნქციას რა დატვირთვა აქვს განსხვავებული როა, ასეთი ლოგიკა თუ გაქ რო თუ ეგეთი ნეიმი არის უკვე არ დაარეგისტრირო, რა მნიშვნელობა აქვს აიდს შეამოწმებ, უსერნეიმს უნიკალურია ხო ორივე, უსერნეიმი ფაქტობრივად აიდია ხო ასეა

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/domain/usecase/start/AuthenticationUseCase.kt
> +
თავისი ბეის კლასი უნდა ამას

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationStartFragment.kt
> +
ცარიელი ხაზი :დ

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationStartFragment.kt
> +            viewModel.startButtonListener(username)
startButtonListener არაა კარგი სახელი

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationStartFragment.kt
> +                }
ექსთენშენი გააკეთე

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationStartFragment.kt
> +                }
ფრაგმენტიდან პირდაპირ ხო შეგიძლია გეთ სტრინგი

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationStartFragment.kt
> +
ცარიელი ხაზები

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationViewModel.kt
> +
ცარიელი ხაზები

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationViewModel.kt
> +    )
გააკეთე რამე ოპტიმალური ფუნქცია კლასი რაც იქნება საჭირო რო ყოველ ჯერზე არ მოგიწიოს _flow da flow გაკეთება

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationViewModel.kt
> +    private fun startButtonProcess(username: String) {
ეს რა სახელია ფუნქციაზე

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationViewModel.kt
> +        viewModelScope.launch {
ექსთენშენი გააკეთე

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationViewModel.kt
> +    }
ფუნქციის სახელები გაქ არასწორად, საინაფს თუ აკეთებ საინ ინ რატო უნდა ეწეროს

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationViewModel.kt
> +    }
ლოგიკაც არასწორად გაქ მგონია, და მთელი ვიუმოდელი იფ ელსება, ოპტიმიზაცია უნდა

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/base/BaseFragment.kt
> +
ოფენ ფუნქციები არაა ამ ბეისში გასაკეთებელი, როგორც წინა აპლიკაციაში, ისე უნდა ქნა თუ გააკეთებ, ბეიზს თავისი სქრინ ბეისი რო უნდა და მერე იქ უკვე შეგიძლია

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/ui/custom/StartIllustrationBackground.kt
> +class StartIllustrationBackground(context: Context, attrs: AttributeSet) :
არაა კარგი სახელი StartIllustration, საერთოდ Start ამოიღე ხმარებიდან ;დ

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dimen_0_dp">0dp</dimen>
ერთი ხაზიც ეყოფა

2023-06-01 09:54 UTC, Gio481 commented on app/src/main/res/values-night/themes.xml
რატო წაშალე ნაითის თემა

2023-06-01 09:54 UTC, Gio481 commented
start არაა შესაბამისი სახელი ამოიღე საერთოდ ხმარებიდან

2023-06-07 07:42 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quizapp/QuizActivity.kt
> +            supportFragmentManager.findFragmentById(R.id.main_nav_host_fragment) as NavHostFragment
არ სჭირდება, ისეც მუშაობს ნავ გრაფი

2023-06-07 07:43 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quizapp/QuizActivity.kt
> +//ინლაინ/ქროსლაინი/ნოინლაინი ფუნქციები
ზედმეტი კომენტარები გააქრე თორემ ბერიძე ნახავს

2023-06-07 07:48 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quizapp/QuizActivity.kt
> +fun EditText.validateUsername(): Boolean {
ეს აქ რატომ წერია?

2023-06-07 07:49 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quizapp/data/local/database/model/dao/UserDao.kt
> +    suspend fun getUserByIdUser(userId: String): UserEntity
getUserByIdUser or getUserByUserID?

2023-06-07 07:50 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quizapp/data/local/database/model/dao/UserDao.kt
> +    suspend fun isUsernameExist(username: String): Boolean
ფუნქციის სახელი გაუმართავია

2023-06-07 08:01 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quizapp/presentation/auth/AuthenticationViewModel.kt
> +    private fun isStrongUserName(userName: String): Boolean {
ალბათ strong-ზე უკეთესი იქნება თუ დაარქმევ isValidUsername?

2023-06-07 08:09 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/quizapp/presentation/home/HomeFragment.kt
> +                findNavController().navigate(HomeFragmentDirections.actionGlobalLogOut())
ნავიგაცია ვიუ მოდელში გაიტანე

2023-06-07 08:11 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/dialog_question.xml
> +        android:layout_marginStart="5dp"
სტატიკურია

2023-06-07 08:11 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/fragment_home.xml
> +        tools:layout_editor_absoluteX="16dp"
ესეც

2023-06-07 08:15 UTC, gioqemoklidze requested changes

2023-06-07 08:15 UTC, gioqemoklidze commented on app/src/main/AndroidManifest.xml
> +
white space

2023-06-07 08:15 UTC, gioqemoklidze commented on app/src/main/java/com/space/quizapp/QuizActivity.kt
> +            supportFragmentManager.findFragmentById(R.id.main_nav_host_fragment) as NavHostFragment
remove unexpected white spaces below

2023-06-07 08:15 UTC, gioqemoklidze commented on app/src/main/java/com/space/quizapp/common/regex/RegexPattern.kt
> +    // does not start with a period "." or an underscore "_"
use javadoc not //

2023-06-07 08:15 UTC, gioqemoklidze commented on app/src/main/res/values/strings.xml
> +    <string name="invalid_username">სახელის სტრუქტურა არასწორია</string>
white spaaces

2023-06-07 08:15 UTC, gioqemoklidze commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dimen_0_dp">0dp</dimen>
remove white space

2023-06-07 08:15 UTC, gioqemoklidze commented on app/src/main/res/values/colors.xml
> +    <color name="wrong">#DB1D2A</color>
what is success and wrong call colors right names

2023-06-08 06:28 UTC, gioqemoklidze requested changes

2023-06-08 06:28 UTC, gioqemoklidze commented on app/src/main/java/com/space/quizapp/presentation/base/QuizBaseCustomView.kt
> +package com.space.quizapp.presentation.base
why you need that base class ? and if you need it create view package in presentation and base package in it and move it

2023-06-08 06:28 UTC, gioqemoklidze commented on app/src/main/java/com/space/quizapp/presentation/custom/AuthIllustrationBackground.kt
> +class StartIllustrationBackground @JvmOverloads constructor(
file and class have different names change it and move it in view package in presentation

2023-06-08 06:31 UTC, gioqemoklidze commented on app/src/main/java/com/space/quizapp/presentation/custom/AuthIllustrationBackground.kt
> +    }
why is this function empty ? remove it

2023-06-08 11:02 UTC, giorgimurgulia-space commented on app/build.gradle
> +
გავასწორე

2023-06-08 11:02 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/data/local/database/model/dao/UserDao.kt
> +    suspend fun getByIdUser(userId: String): UserEntity
გავასწორე

2023-06-08 11:03 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/data/local/database/model/dao/UserDao.kt
> +    suspend fun getByUsername(username: String): UserEntity
კი მაგრამ id მაქ ცალკე რომელზე მაქ აწყობილი ჩემ მხარეს ყვეაფერი.

2023-06-08 11:03 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationStartFragment.kt
> +
გავასწორე

2023-06-08 11:05 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationStartFragment.kt
> +                }
გავასწორე

2023-06-08 11:05 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationStartFragment.kt
> +                }
ვიუმოდელი აწვდის int ს და ფრაგმენტი იღებს

2023-06-08 11:06 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationStartFragment.kt
> +
გავასწორე

2023-06-08 11:06 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationViewModel.kt
> +    private fun startButtonProcess(username: String) {
გავასწორე

2023-06-08 11:06 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationViewModel.kt
> +        viewModelScope.launch {
გავასწორე

2023-06-08 11:07 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationViewModel.kt
> +    }
საიაფის მერე საინ ინს აკეთებს ავტომატურად

2023-06-08 11:07 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/ui/auth/AuthenticationViewModel.kt
> +    }
გადავაკეთე

2023-06-08 11:09 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/ui/custom/StartIllustrationBackground.kt
> +class StartIllustrationBackground(context: Context, attrs: AttributeSet) :
გადავაკეთე

2023-06-08 11:09 UTC, giorgimurgulia-space commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dimen_0_dp">0dp</dimen>
გავასწორე

2023-06-08 11:09 UTC, giorgimurgulia-space commented on app/src/main/res/values-night/themes.xml
აპპ ში არ გვაქ ნათი მოუდი

2023-06-08 11:09 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/QuizActivity.kt
> +            supportFragmentManager.findFragmentById(R.id.main_nav_host_fragment) as NavHostFragment
წავშალე

2023-06-08 11:09 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/QuizActivity.kt
> +//ინლაინ/ქროსლაინი/ნოინლაინი ფუნქციები
წავშალე

2023-06-08 11:09 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/QuizActivity.kt
> +fun EditText.validateUsername(): Boolean {
წავშალე

2023-06-08 11:10 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/data/local/database/model/dao/UserDao.kt
> +    suspend fun getUserByIdUser(userId: String): UserEntity
გავასწორე

2023-06-08 11:10 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/data/local/database/model/dao/UserDao.kt
> +    suspend fun isUsernameExist(username: String): Boolean
გავასწორე

2023-06-08 11:10 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/presentation/auth/AuthenticationViewModel.kt
> +    private fun isStrongUserName(userName: String): Boolean {
გავასწორე

2023-06-08 11:10 UTC, giorgimurgulia-space commented on app/src/main/res/layout/dialog_question.xml
> +        android:layout_marginStart="5dp"
გავასწორე

2023-06-08 11:10 UTC, giorgimurgulia-space commented on app/src/main/res/layout/fragment_home.xml
> +        tools:layout_editor_absoluteX="16dp"
გავასწორე

2023-06-08 11:11 UTC, giorgimurgulia-space commented on app/src/main/AndroidManifest.xml
> +
გავასწორე

2023-06-08 11:11 UTC, giorgimurgulia-space commented on app/src/main/res/values/strings.xml
> +    <string name="invalid_username">სახელის სტრუქტურა არასწორია</string>
გავასწორე

2023-06-08 11:12 UTC, giorgimurgulia-space commented on app/src/main/res/values/colors.xml
> +    <color name="wrong">#DB1D2A</color>
გავასწორე

2023-06-08 11:13 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/presentation/base/QuizBaseCustomView.kt
> +package com.space.quizapp.presentation.base
done

2023-06-08 11:13 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/presentation/custom/AuthIllustrationBackground.kt
> +class StartIllustrationBackground @JvmOverloads constructor(
done

2023-06-08 11:14 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/presentation/custom/AuthIllustrationBackground.kt
> +    }
done

2023-06-08 12:31 UTC, ninikokra approved these changes

2023-06-08 12:54 UTC, DavitTsiskarashvili approved these changes

2023-06-13 09:51 UTC, merged