[cmob_1719]/feature/quiz page
giorgimurgulia-space/QuizApp pull request #3
Opened 2023-06-20 12:23 UTC by giorgimurgulia-space

https://spaceneobank.atlassian.net/browse/CMOB-1719

2023-06-21 10:04 UTC, AnaRusadze requested changes

2023-06-21 10:04 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/common/AnswerStatus.kt
> +}
POSITIVE და CORRECT იგივეა. ერთ-ერთი ამოიღე

2023-06-21 10:04 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/common/mapper/Mappers.kt
> +fun UserPointEntity.toAvailableQuizModel() =
toAvailable რატომ?

2023-06-21 10:04 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/data/repository/CurrentQuizRepositoryImpl.kt
> +                userPoint += 1
კაი იქნება რომ თითოეული პასუხის დატაკლასს ექნება ქულის რაოდენობის ცვლადი, რომელიც დეფოლტად 1 იქნება და ამ ცვლადით გავაკონტროლებთ ქულების ზრდას. ასე იმ შემთხვევებსაც დავჰენდლავთ, თუ მოთხოვნა წამოვა, რომ სხვადასხვა პასუხი სხვადასხვა ქულიანი იყოს

2023-06-21 10:04 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/presentation/home/vm/HomeViewModel.kt
> +    private val _state = MutableStateFlow(UserUIModel("", "", "0"))
UserUIModel("", "", "0") ცარიელი სტრინგებით და ნული არასდროს გადააწოდო. თუ სხვანაირად არ გამოდის თვითონ UserUIModel ში პარამეტრები შეგიძლია ნალეიბლი გახადო და დეფოლტ მნიშვნელობები ნალი დაუწერო. რომ ცარიელი ობიექტი შეგიქმნას. იდეალური ვარიანტი ეგეც არაა, მაგრამ ამაზე მისაღები იქნება

2023-06-21 10:04 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/presentation/quiz/adapter/AnswerAdapter.kt
> +            }
წინა შეხვედრაზე განვიხილეთ, რომ შეიძლება სეტონქლიქლისენერის onCreateViewHolderში გადატანა, რომ მხოლოდ ერთხელ მოხდეს დასეტვა. პარასკევის შეხვედრის ჩატში დოკუმენტაციაც ჩააგდეს და გადახედე

2023-06-21 10:04 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/presentation/quiz/adapter/AnswerAdapter.kt
> +        fun onItemClick(answerIndex: Int)
ლამბდად გადააკეთე

2023-06-21 10:04 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/presentation/quiz/ui/QuizFragment.kt
> +    }
binding.submitButton.text = resources.getString(if(isLastQuestion) R.string.finish else R.string.next))

2023-06-21 10:04 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/presentation/quiz/vm/QuizViewModel.kt
> +    private val _quizState = MutableStateFlow(QuizPagePayLoad("", "", Result.Loading, false, null))
QuizPagePayLoad აქაც იგივე, დეფოლტ მნიშვნელობები შეგიძლია კლასის შიგნით დაუწერო

2023-06-21 10:04 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/presentation/quiz/vm/QuizViewModel.kt
> +        return finishQuiz()
cancelQuiz სახელის მიხედვით არაფერს არეთარნებს. თუ ქულების დაბრუნება გინდა getQuizPoints უნდა ერქვას

2023-06-21 10:04 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/presentation/view/AnswerView.kt
> +                }
CORRECT და POSITIVE-ს იგივე ლოგიკა აქვს. რევიუზე კარგად აგვიხსენი რა განსხვავებაა

2023-06-21 10:04 UTC, AnaRusadze commented on app/src/main/res/layout/dialog_message.xml
> +        android:id="@+id/close_button"
აიდის სახელები camelCaseით ჯობია closeButton მაგალითად

2023-06-21 10:21 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/common/mapper/Mappers.kt
> +fun UserPointEntity.toAvailableQuizModel() =
გავასწორე

2023-06-21 10:28 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/presentation/home/vm/HomeViewModel.kt
> +    private val _state = MutableStateFlow(UserUIModel("", "", "0"))
გავასწორე

2023-06-21 10:29 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/presentation/quiz/ui/QuizFragment.kt
> +    }
გავასწორე

2023-06-21 10:33 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/presentation/quiz/vm/QuizViewModel.kt
> +    private val _quizState = MutableStateFlow(QuizPagePayLoad("", "", Result.Loading, false, null))
გავასწორე

2023-06-21 10:33 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/presentation/quiz/vm/QuizViewModel.kt
> +        return finishQuiz()
გავასწორე

2023-06-21 10:39 UTC, giorgimurgulia-space commented on app/src/main/res/layout/dialog_message.xml
> +        android:id="@+id/close_button"
აქამდენ ყველაგნ _ ებით ვწერდი ამის შემდეგ გადავალ id_ებზე camelCase_ზე

2023-06-21 10:57 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/data/repository/CurrentQuizRepositoryImpl.kt
> +                userPoint += 1
ცალკე ბრენჩზე გადავაწყობ რო ქვიზს ქონდეს ქულა და ის ქულავე დაბრუნდეს პასუხში.
აპი დოკუემნატციაშიც დავამატებ ქულას თუ პრობლემა არ იქნება.

2023-06-22 10:31 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/common/AnswerStatus.kt
> +}
გადავაკეთე ადაპტერი, შესაბამისად აღარ მჭირდება სტატუსია

2023-06-22 10:31 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/presentation/view/AnswerView.kt
> +                }
გადავაკეთე ადაპტერი, შესაბამისად აღარ მჭირდება სტატუსია

2023-06-22 15:53 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/presentation/quiz/adapter/AnswerAdapter.kt
> +            }
გავასწორე

2023-06-22 15:53 UTC, giorgimurgulia-space commented on app/src/main/java/com/space/quizapp/presentation/quiz/adapter/AnswerAdapter.kt
> +        fun onItemClick(answerIndex: Int)
გადავაკეთე

2023-06-23 09:18 UTC, AnaRusadze approved these changes

2023-06-23 11:05 UTC, DavitTsiskarashvili approved these changes

2023-06-23 12:56 UTC, ninikokra approved these changes

2023-06-23 13:28 UTC, merged